# Rime default settings
# encoding: utf-8

config_version: '0.40'

schema_list:

  - schema: tiger_simple    # 虎码单字
  - schema: tiger           # 虎码整句
  # - schema: moqi_xh # 墨奇辅助码 鹤拼版 大词库版本 非自动上屏，支持4万字
  - schema: moqi_zrm # 墨奇辅助码 自然双拼版 大词库版本 非自动上屏，支持4万字
  #- schema: flypy_flypy # 鹤形+鹤拼, 小鹤官方就只有8000字左右
  #- schema: zrm_zrm # 自然码+自然码部首辅助码
  #- schema: moqi_single_xh # 墨奇码·顶屏版·小鹤双拼，为了4码自动上屏 只收录了8000字
  # - schema: moqi_sogou # 墨奇辅助码搜狗双拼版 大词库版本 非自动上屏，支持4万字
  # - schema: moqi_ms # 墨奇辅助码微软双拼版 大词库版本 非自动上屏，支持4万字
  # - schema: luna_pinyin
  # - schema: luna_pinyin_simp
  # - schema: luna_pinyin_fluency
  # - schema: bopomofo
  # - schema: bopomofo_tw
  # - schema: cangjie5
  # - schema: stroke
  # - schema: terra_pinyin
  # - schema: moran
  # - schema: moran_fixed
  # - schema: moran_sentence
  # - schema: moran_aux
  # - schema: moran_bj


switcher:
  caption: 〔方案選單〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - traditionalization
    - extended_charset
    - zh_hant
    - zh_hans
    - zh_hant_tw
    - emoji
    - inflexible
    - unicode_comment
  fold_options: true
  abbreviate_options: true
  option_list_separator: '／'

menu:
  page_size: 6

punctuator:
  full_shape:
    __include: punctuation:/full_shape
  half_shape:
    __include: punctuation:/half_shape

key_binder:
  bindings:
    __patch:
      - key_bindings:/emacs_editing
      - key_bindings:/move_by_word_with_tab
      - key_bindings:/paging_with_minus_equal
      - key_bindings:/numbered_mode_switch
      - key_bindings:/paging_with_comma_period

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: commit_code
    Shift_R: commit_text
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
